runtime: python39
entrypoint: gunicorn -b :$PORT main:app

env_variables:
  GOOGLE_CLOUD_PROJECT: "assignment-1-417320"
  GCLOUD_STORAGE_BUCKET: "ass_cloud1"

handlers:
- url: /static
  static_dir: static/
- url: /.*
  script: auto
